#define NUM_ROWS 16
#define NUM_COLS 16
#define NUMPLANE 3
#define UNUM_ROWS 16U
#define UNUM_COLS 16U

#define RANDOM_SUPPORT
#define SCROLLTEXT_SUPPORT
#define SCROLLTEXT_FONT FONT_ARIAL8
#define SCROLLTEXT_BUFFER_SIZE 128
#define SCROLL_X_SPEED 20
#define SCROLL_Y_SPEED 20
#define SCROLLTEXT_TEXT "</#  Boekhoff    "
#define JOYSTICK_SUPPORT

#define GAME_BASTET
#define GAME_SNAKE
#define ANIMATION_TIME
#define ANIMATION_SCROLLTEXT
#define ANIMATION_SPIRAL
#define ANIMATION_FIRE
#define ANIMATION_TESTS
#define ANIMATION_CHECKERBOARD
#define GAME_TETRIS_CORE
#define GAME_TETRIS
#define MENU_SUPPORT
#define GAME_TETRIS_FP
#define GAME_SPACE_INVADERS
#define GAME_SNAKE
#define GAME_BREAKOUT

#define ANIMATION_SCROLLTEXT
#define ANIMATION_SPIRAL
#define SPIRAL_DELAY 5
#define ANIMATION_JOERN1
#define ANIMATION_SNAKE
#define SNAKE_GAME_DELAY 200
#define SNAKE_ANIM_DELAY 100
#define SNAKE_TERMINATION_DELAY 60
#define SNAKE_MAX_LENGTH 64
#define SNAKE_MAX_APPLES 10
#define ANIMATION_CHECKERBOARD
#define ANIMATION_FIRE
#define FIRE_S 30
#define FIRE_N 5
#define FIRE_DIV 44
#define FIRE_DELAY 50
#define FIRE_CYCLES 800
#define ANIMATION_MATRIX
#define MATRIX_STREAMER_NUM 30
#define MATRIX_CYCLES 500
#define MATRIX_DELAY 60
#define ANIMATION_RANDOM_BRIGHT
#define ANIMATION_STONEFLY
#define ANIMATION_FLYINGDOTS
#define ANIMATION_GAMEOFLIFE
#define GOL_DELAY 100
#define GOL_CYCLES 360
#define ANIMATION_BREAKOUT
#define ANIMATION_MHERWEG
#define ANIMATION_MOIRE
#define ANIMATION_LTN_ANT
#define ANIMATION_TIME
#define ANIMATION_BMSCROLLER
#define ANIMATION_LABORLOGO
//ANIMATION_AMPHIBIAN
//ANIMATION_LOGO_OOS
#define ANIMATION_FAIRYDUST
#define ANIMATION_PLASMA
#define FP_PLASMA_DELAY 1
#define ANIMATION_PSYCHEDELIC
#define FP_PSYCHO_DELAY 15
//ANIMATION_BLACKHOLE
//ANIMATION_SQUARES
#define ANIMATION_TESTS
#define ANIMATION_OFF

#
//small Animations
#
//SMALLANIMATION_ROWWALK
#define SMALLANIMATION_ROWWALK_SPEED 50
#define SMALLANIMATION_ROWWALK_COUNT 10
//SMALLANIMATION_COLWALK
#define SMALLANIMATION_COLWALK_SPEED 50
#define SMALLANIMATION_COLWALK_COUNT 10
//SMALLANIMATION_ROWBOUNCE
#define SMALLANIMATION_ROWBOUNCE_SPEED 50
#define SMALLANIMATION_ROWBOUNCE_COUNT 10
//SMALLANIMATION_COLBOUNCE
#define SMALLANIMATION_COLBOUNCE_SPEED 50
#define SMALLANIMATION_COLBOUNCE_COUNT 10

