#include "config.h"
extern "C" {
    #include "pixel.h"
    //#include "mcuf/mcuf.c"
    #include "display_loop.h"
    #include "user/user_loop.c"
    #include "eeprom_reserve.c"
    #include "scrolltext/font_c64.c"
    #include "scrolltext/font_arial8.c"
    #include "scrolltext/font_small6.c"
    #include "scrolltext/font_uni53.c"
    #include "scrolltext/scrolltext3.c"
    #include "menu/menu.c"
    //#include "joystick/rfm12_joystick.c"
    #include "joystick/null_joystick.c"
    //#include "joystick/nes_pad.c"
    //#include "joystick/hc165_joystick.c"
    //#include "joystick/joystick.c"
    //#include "joystick/lolshield_joystick.c"
    #include "random/noekeon.c"
    #include "random/prng.c"
    #include "random/persistentCounter.c"
    #include "random/memxor_c.c"
    #include "smallani/rowwalk.c"
    #include "smallani/rowbounce.c"
    #include "smallani/colwalk.c"
    #include "smallani/colbounce.c"
    #include "games/kart/kart.c"
    #include "games/tetris/variant_fp.c"
    #include "games/tetris/variant_bastet.c"
    #include "games/tetris/input.c"
    #include "games/tetris/variant_std.c"
    #include "games/tetris/highscore.c"
    #include "games/tetris/piece.c"
    #include "games/tetris/bucket.c"
    #include "games/tetris/tetris_main.c"
    #include "games/tetris/view.c"
    #include "games/space_invaders/invader_proc.c"
    #include "games/space_invaders/invaders2.c"
    #include "games/space_invaders/invader_init.c"
    #include "games/space_invaders/invader_draw.c"
    #include "games/breakout/level.c"
    #include "games/breakout/playfield.c"
    #include "games/breakout/rebound.c"
    #include "games/breakout/score.c"
    #include "games/breakout/messages.c"
    #include "games/breakout/ball.c"
    #include "games/breakout/breakout.c"
    #include "games/snake/snake_game.c"
    //#include "uart/uart_commands.c"
    //#include "uart/uart.c"
    #include "animations/breakout_demo.c"
    #include "animations/flyingdots.c"
    #include "animations/squares.c"
    #include "animations/ltn_ant.c"
    #include "animations/stonefly.c"
    #include "animations/program.c"
    #include "animations/snake.c"
    #include "animations/gameoflife.c"
    #include "animations/dna.c"
    #include "animations/blackhole.c"
    #include "animations/fpmath_patterns.c"
    #include "animations/mherweg.c"
    #include "animations/bitmapscroller/amphibian.c"
    #include "animations/bitmapscroller/outofspec.c"
    #include "animations/bitmapscroller/fairydust.c"
    #include "animations/bitmapscroller/laborlogo.c"
    #include "animations/bitmapscroller/bitmapscroller.c"
    #include "animations/bitmapscroller/thisisnotdetroit.c"
    #include "animations/moire.c"
    //#include "animations/borg_time.c"
    #include "animations/matrix.c"
    void pixel_init();
}
    
void setup() {
    pixel_init();
}

void loop() {
    display_loop();
}

